import { Tile } from "../Enums/Tile";
import { Combination } from "../Models/Combination";

export const combinations = [
  {
    firstTile: Tile.HIVE,
    secondTile: Tile.KILL,
    thirdTile: Tile.WORM,
    isTruth: false,
  },
  {
    firstTile: Tile.HIVE,
    secondTile: Tile.STOP,
    thirdTile: Tile.WITNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.HIVE,
    secondTile: Tile.GIVE,
    thirdTile: Tile.DARKNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.HIVE,
    secondTile: Tile.KILL,
    thirdTile: Tile.LIGHT,
    isTruth: false,
  },
  {
    firstTile: Tile.WITNESS,
    secondTile: Tile.KILL,
    thirdTile: Tile.PYRAMID,
    isTruth: false,
  },
  {
    firstTile: Tile.WITNESS,
    secondTile: Tile.DRINK,
    thirdTile: Tile.LIGHT,
    isTruth: false,
  },
  {
    firstTile: Tile.TRAVELLER,
    secondTile: Tile.DRINK,
    thirdTile: Tile.WORM,
    isTruth: false,
  },
  {
    firstTile: Tile.TRAVELLER,
    secondTile: Tile.GIVE,
    thirdTile: Tile.HIVE,
    isTruth: false,
  },
  {
    firstTile: Tile.TRAVELLER,
    secondTile: Tile.KILL,
    thirdTile: Tile.GUARDIAN,
    isTruth: false,
  },
  {
    firstTile: Tile.TRAVELLER,
    secondTile: Tile.STOP,
    thirdTile: Tile.WITNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.LIGHT,
    secondTile: Tile.STOP,
    thirdTile: Tile.SAVATHÛN,
    isTruth: false,
  },
  {
    firstTile: Tile.PYRAMID,
    secondTile: Tile.DRINK,
    thirdTile: Tile.GUARDIAN,
    isTruth: false,
  },
  {
    firstTile: Tile.PYRAMID,
    secondTile: Tile.STOP,
    thirdTile: Tile.WITNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.GUARDIAN,
    secondTile: Tile.WORSHIP,
    thirdTile: Tile.WITNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.GUARDIAN,
    secondTile: Tile.KILL,
    thirdTile: Tile.TRAVELLER,
    isTruth: false,
  },
  {
    firstTile: Tile.SAVATHÛN,
    secondTile: Tile.STOP,
    thirdTile: Tile.DARKNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.SAVATHÛN,
    secondTile: Tile.DRINK,
    thirdTile: Tile.DARKNESS,
    isTruth: false,
  },
  {
    firstTile: Tile.PYRAMID,
    secondTile: Tile.GIVE,
    thirdTile: Tile.DARKNESS,
    isTruth: true,
  },
  {
    firstTile: Tile.PYRAMID,
    secondTile: Tile.STOP,
    thirdTile: Tile.SAVATHÛN,
    isTruth: true,
  },
  {
    firstTile: Tile.PYRAMID,
    secondTile: Tile.KILL,
    thirdTile: Tile.WORM,
    isTruth: true,
  },
  {
    firstTile: Tile.PYRAMID,
    secondTile: Tile.DRINK,
    thirdTile: Tile.WORM,
    isTruth: true,
  },
  {
    firstTile: Tile.HIVE,
    secondTile: Tile.WORSHIP,
    thirdTile: Tile.DARKNESS,
    isTruth: true,
  },
  {
    firstTile: Tile.HIVE,
    secondTile: Tile.WORSHIP,
    thirdTile: Tile.WORM,
    isTruth: true,
  },
  {
    firstTile: Tile.TRAVELLER,
    secondTile: Tile.GIVE,
    thirdTile: Tile.GUARDIAN,
    isTruth: true,
  },
  {
    firstTile: Tile.TRAVELLER,
    secondTile: Tile.GIVE,
    thirdTile: Tile.LIGHT,
    isTruth: true,
  },
  {
    firstTile: Tile.GUARDIAN,
    secondTile: Tile.KILL,
    thirdTile: Tile.WITNESS,
    isTruth: true,
  },
  {
    firstTile: Tile.GUARDIAN,
    secondTile: Tile.WORSHIP,
    thirdTile: Tile.LIGHT,
    isTruth: true,
  },
  {
    firstTile: Tile.GUARDIAN,
    secondTile: Tile.WORSHIP,
    thirdTile: Tile.TRAVELLER,
    isTruth: true,
  },
  {
    firstTile: Tile.DARKNESS,
    secondTile: Tile.STOP,
    thirdTile: Tile.SAVATHÛN,
    isTruth: true,
  },
] as Combination[];
